/* tslint:disable */
/* eslint-disable */
/**
 * Retreaver Core API
 * The Retreaver Core API can be used to automate core business processes, like changing where calls are routed, and many other features that would normally be accessed through our account portal.  **Authentication**: All requests require an API key passed as a query parameter `api_key`. If you have access to multiple companies, also pass `company_id`.  **Format**: The API supports both JSON and XML. Use `.json` or `.xml` file extensions in the URL and set the appropriate Content-Type header.  **Pagination**: Returns 25 results per page. Use the Link HTTP header to navigate pages.  **Security Warning**: Never expose your API key publicly as it can be used to access your entire Retreaver account without restriction!
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CallV1 {
  /**
   * Unique identifier for the call
   */
  uuid?: string;
  /**
   * Caller\'s phone number in E.164 format
   */
  caller?: string;
  /**
   * Caller\'s ZIP code
   */
  caller_zip?: string | null;
  /**
   * Caller\'s state
   */
  caller_state?: string | null;
  /**
   * Caller\'s city
   */
  caller_city?: string | null;
  /**
   * Caller\'s country code
   */
  caller_country?: string | null;
  /**
   * Duration of the connected call in seconds
   */
  dialed_call_duration?: number;
  /**
   * Total duration including IVR and hold time in seconds
   */
  total_duration?: number;
  /**
   * Call status
   */
  status?: CallV1StatusEnum;
  /**
   * When the call started
   */
  start_time?: string;
  /**
   * When the call was forwarded to target
   */
  forwarded_time?: string | null;
  /**
   * When the call ended
   */
  end_time?: string | null;
  /**
   * Campaign ID
   */
  cid?: string;
  /**
   * Affiliate ID
   */
  afid?: string | null;
  /**
   * Sub ID
   */
  sid?: string | null;
  /**
   * Number that was dialed
   */
  dialed_number?: string;
  /**
   * URL to call recording
   */
  recording_url?: string | null;
  updated_at?: string;
  created_at?: string;
}

export enum CallV1StatusEnum {
  Finished = 'finished',
  InProgress = 'in_progress',
}
