/* tslint:disable */
/* eslint-disable */
/**
 * Retreaver Core API
 * The Retreaver Core API can be used to automate core business processes, like changing where calls are routed, and many other features that would normally be accessed through our account portal.  **Authentication**: All requests require an API key passed as a query parameter `api_key`. If you have access to multiple companies, also pass `company_id`.  **Format**: The API supports both JSON and XML. Use `.json` or `.xml` file extensions in the URL and set the appropriate Content-Type header.  **Pagination**: Returns 25 results per page. Use the Link HTTP header to navigate pages.  **Security Warning**: Never expose your API key publicly as it can be used to access your entire Retreaver account without restriction!
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BusinessHours } from './business-hours';
// May contain unused imports in some cases
// @ts-ignore
import type { Cap } from './cap';
// May contain unused imports in some cases
// @ts-ignore
import type { TagValue } from './tag-value';

export interface Target {
    /**
     * Internal target ID
     */
    'id'?: number;
    /**
     * Phone number or SIP endpoint
     */
    'number'?: string;
    /**
     * Descriptive name for the target
     */
    'name'?: string;
    /**
     * Your custom target ID
     */
    'tid'?: string | null;
    /**
     * Lower priority targets are considered first
     */
    'priority'?: number;
    /**
     * Used to randomize order of same-priority targets
     */
    'weight'?: number;
    /**
     * Max seconds to wait while ringing
     */
    'timeout_seconds'?: number;
    /**
     * DTMF tones to send when answered (use \'w\' for 0.5s pause)
     */
    'send_digits'?: string | null;
    /**
     * Max concurrent calls allowed
     */
    'concurrency_cap'?: number | null;
    /**
     * Paused targets won\'t receive calls
     */
    'paused'?: boolean;
    /**
     * Time zone for business hours
     */
    'time_zone'?: string;
    'sip_username'?: string | null;
    'sip_password'?: string | null;
    'caps'?: Array<Cap>;
    'business_hours'?: Array<BusinessHours>;
    'tag_values'?: Array<TagValue>;
    'created_at'?: string;
    'updated_at'?: string;
}

